=== Jniecor/JulioNieto_ExUD4_LMSGI/Ejercicio 1/Sucursales.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            <Descripción>Información de las sucursales</Descripción>
            <Fecha>14/02/2022</Fecha>
            <Autor>Julio Nieto Cordón</Autor>
        </xs:documentation>
    </xs:annotation>
    <xs:element name="Sucursales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sucursal" maxOccurs="unbounded"> 
                    <xs:complexType>
                        <xs:attribute name="código" type="SucursalCódigo"/>
                    </xs:complexType>
                </xs:element>   
                        <xs:sequence>
                                <xs:element name="Pedido" type="xs:string"></xs:element>
                                    <xs:sequence>
                                        <xs:element name="Nomb_trabajador" type="xs:string"></xs:element>
                                        <xs:element name="Fecha" type="xs:string"></xs:element>
                                        <xs:element name="Observación" type="xs:string"></xs:element>
                                        <xs:element name="Artículo" type="xs:string"></xs:element>
                                            <xs:sequence>
                                                <xs:element name="Unidades" type="xs:int"></xs:element>
                                                <xs:element name="Precio" type="xs:int"></xs:element>
                                                <xs:element name="Observaciones" type="xs:string"></xs:element>
                                                <xs:element name="Plazo_de_revisión" type="xs:string"></xs:element>
                                            </xs:sequence>
                                    </xs:sequence>
                            </xs:sequence>
                    </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jniecor/JulioNieto_ExUD4_LMSGI/Ejercicio 1/Sucursales_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Sucursales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Sucursales.xsd">
    <Sucursal código="A0000001">
        <Pedido>
            <Nomb_trabajador>Antonio Mendoza</Nomb_trabajador>
            <Fecha>12/12/2022</Fecha>
            <Observaciones>Urgente</Observaciones>
            <Artículo código="AAA-001">
                <Unidades>2</Unidades>
                <Precio>10€</Precio>
                <Observaciones>Frágil</Observaciones>
                <Plazo_de_revisión>15/12/2022-16/12/2022</Plazo_de_revisión>
            </Artículo>
            <Artículo código="AAA-002">
                <Unidades>1</Unidades>
                <Precio>35€</Precio>
                <Observaciones>Frágil</Observaciones>
                <Plazo_de_revisión>15/12/2022-16/12/2022</Plazo_de_revisión>
            </Artículo>
        </Pedido>
    </Sucursal>
    <Sucursal código="A0000002">
        <Pedido>
            <Nomb_trabajador>Jorge Márquez</Nomb_trabajador>
            <Fecha>14/8/2022</Fecha>
            <Observaciones>Incompleto</Observaciones>
            <Artículo código="AAA-003">
                <Unidades>1</Unidades>
                <Precio>105€</Precio>
                <Observaciones>Frágil</Observaciones>
                <Plazo_de_revisión>15/8/2022-17/8/2022</Plazo_de_revisión>
            </Artículo>
        </Pedido>
    </Sucursal>
</Sucursales>
